# Generated by Django 2.0.4 on 2018-04-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='points',
        ),
        migrations.AddField(
            model_name='choice',
            name='comment',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
