# Generated by Django 2.0.4 on 2018-04-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180420_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='comment',
        ),
    ]
