# Generated by Django 2.0.4 on 2018-04-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_text',
        ),
    ]
